---
# tasks file for vpcyaml

# Create The VPC
- name: Create a VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: "{{ vpc_state }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    tags:
      Name: "{{ vpc_name }}"
      Description: "{{ vpc_desc }}"
    tenancy: "{{ vpc_tenancy }}"
  register: vpc_result

# Create A Subnet
- name: Create a subnet
  ec2_vpc_subnet:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
    az: "{{ az1 }}"
    cidr: "{{ subnet1_cidr }}"
    map_public: yes
    wait: yes
    state: "{{ subnet1_state }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    tags: 
      Name: "{{ vpc_name }}-subnet1"
      Purpose: "Public_subnet" 
  register: subnet1_result
  when: vpc_result.vpc.id is defined



