---
# tasks file for vpcyaml

# Create The VPC
- name: Create a VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: "{{ vpc_state }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    tags:
      Name: "{{ vpc_name }}"
      Description: "{{ vpc_desc }}"
    tenancy: "{{ vpc_tenancy }}"
  register: vpc_result

# Create A Subnet


